# Generated by Django 5.2.8 on 2025-11-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctorprofile",
            options={"verbose_name": "医生档案", "verbose_name_plural": "医生档案"},
        ),
        migrations.AlterModelOptions(
            name="salesprofile",
            options={"verbose_name": "销售档案", "verbose_name_plural": "销售档案"},
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="department",
            field=models.CharField(
                help_text="【业务说明】所属科室；【用法】帮助患者识别；【示例】肿瘤科；【参数】str；【返回值】str",
                max_length=50,
                verbose_name="* 所属科室",
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="hospital",
            field=models.CharField(
                help_text="【业务说明】所属医院；【用法】展示/筛选；【示例】上海市第一人民医院；【参数】str；【返回值】str",
                max_length=100,
                verbose_name="* 所属医院",
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="name",
            field=models.CharField(
                help_text="【业务说明】医生姓名；【用法】前端展示；【示例】张主任；【参数】str；【返回值】str",
                max_length=50,
                verbose_name="* 医生姓名",
            ),
        ),
    ]
