# Generated by Django 5.2.8 on 2025-11-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_patientprofile_age_patientprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='qrcode_expire_at',
            field=models.DateTimeField(blank=True, help_text='【业务说明】记录二维码失效时间，避免频繁请求微信；【用法】每次生成更新；【示例】2025-01-01 10:00；【参数】datetime；【返回值】datetime', null=True, verbose_name='二维码过期时间'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='qrcode_url',
            field=models.URLField(blank=True, help_text='【业务说明】缓存患者绑定二维码 URL；【用法】销售端展示扫码绑定；【示例】https://wx.qq.com/qrcode；【参数】str；【返回值】str', verbose_name='绑定二维码'),
        ),
    ]
