# Generated by Django 5.2.8 on 2025-11-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_patientrelation_is_primary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='sales',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='sales',
            field=models.ManyToManyField(blank=True, help_text='【业务说明】负责维护该医生的销售团队；【用法】绩效归属；【示例】SalesProfile#2；【参数】多选；【返回值】SalesProfile', related_name='doctors', to='users.salesprofile', verbose_name='负责销售团队'),
        ),
    ]
