# Generated by Django 5.2.8 on 2025-11-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_doctorprofile_sales_doctorprofile_sales"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientprofile",
            name="service_status",
        ),
    ]
