# Generated by Django 5.2.8 on 2025-11-27 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_patientprofile_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bound_sales',
            field=models.ForeignKey(blank=True, help_text='【业务说明】记录未建档潜客归属；【用法】销售跟进；【示例】SalesProfile#1；【参数】外键；【返回值】SalesProfile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='users.salesprofile', verbose_name='潜客归属销售'),
        ),
    ]
