# Generated by Django 5.2.8 on 2025-11-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_bound_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesprofile',
            name='qrcode_url',
            field=models.URLField(blank=True, help_text='【业务说明】微信永久二维码链接；【用法】缓存以减少 API 调用', verbose_name='永久二维码'),
        ),
    ]
