# Generated by Django 5.2.8 on 2025-12-01 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_patientrelation_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientprofile",
            name="device_sn",
        ),
    ]
