# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_patientprofile_indicator_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantprofile",
            name="patient_chat_permission",
            field=models.CharField(
                choices=[
                    ("allowed", "允许和患者聊天"),
                    ("disabled", "禁止和患者聊天"),
                ],
                default="allowed",
                help_text="【业务说明】控制助理是否可在患者会话发言；【用法】禁用后仅限制患者会话发送，不影响查看与内部沟通；【示例】allowed；【参数】枚举字符串；【返回值】str",
                max_length=20,
                verbose_name="患者聊天权限",
            ),
        ),
    ]
