# Generated by Django 5.2.8 on 2026-05-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_assistantprofile_patient_chat_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='baseline_height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='【业务说明】患者身高参考值，用于完整记录生命体征基线；【用法】由医生在管理端配置；【示例】170.5；【参数】decimal；【返回值】decimal', max_digits=5, null=True, verbose_name='身高基线(cm)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='ethnicity',
            field=models.CharField(blank=True, help_text='【业务说明】患者人口学信息；【用法】医生建档或随访补充；【示例】汉族；【参数】str；【返回值】str', max_length=20, verbose_name='民族'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='marital_status',
            field=models.CharField(blank=True, help_text='【业务说明】患者人口学信息；【用法】医生建档或随访补充；【示例】已婚；【参数】str；【返回值】str', max_length=20, verbose_name='婚姻状况'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='native_place',
            field=models.CharField(blank=True, help_text='【业务说明】患者人口学信息；【用法】医生建档或随访补充；【示例】江苏南京；【参数】str；【返回值】str', max_length=100, verbose_name='籍贯'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='occupation',
            field=models.CharField(blank=True, help_text='【业务说明】患者人口学信息；【用法】医生建档或随访补充；【示例】退休；【参数】str；【返回值】str', max_length=50, verbose_name='职业'),
        ),
    ]
