# Generated by Django 5.2.8 on 2025-11-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime', verbose_name='更新时间')),
                ('code', models.CharField(db_index=True, help_text='【程序员看】唯一标识，代码中通过此字段获取文案。例如：bind_success_self', max_length=50, unique=True, verbose_name='模版编码')),
                ('title', models.CharField(help_text='【运营看】描述这个文案是用在哪里的。', max_length=100, verbose_name='模版名称')),
                ('content', models.TextField(help_text='支持变量替换。例如：你好，{name}。请确保变量名与开发约定一致。', verbose_name='文案内容')),
                ('available_vars', models.CharField(blank=True, help_text='备注提示，例如：{name}=患者姓名, {doctor}=医生姓名', max_length=255, verbose_name='可用变量说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '微信消息文案库',
                'verbose_name_plural': '微信消息文案库',
            },
        ),
    ]
