# Generated by Django 5.2.8 on 2025-12-01 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0012_remove_patientprofile_device_sn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime', verbose_name='更新时间')),
                ('sn', models.CharField(db_index=True, help_text='【业务说明】设备唯一物理标识；【来源】扫描字段 sn；【示例】ZK204X...', max_length=64, unique=True, verbose_name='设备SN码')),
                ('imei', models.CharField(blank=True, help_text='【业务说明】蜂窝网络标识，如有则必须唯一；【来源】扫描字段 imei', max_length=64, unique=True, verbose_name='IMEI')),
                ('model_name', models.CharField(blank=True, help_text='【来源】扫描字段 model，如 ZK204', max_length=64, verbose_name='硬件型号')),
                ('ble_name', models.CharField(blank=True, help_text='【来源】扫描字段 ble，用于蓝牙连接匹配', max_length=64, verbose_name='蓝牙广播名')),
                ('firmware_version', models.CharField(blank=True, help_text='【来源】扫描字段 version，用于判断是否需要 OTA 升级', max_length=64, verbose_name='固件版本')),
                ('device_type', models.PositiveSmallIntegerField(choices=[(1, '智能手表')], default=1, help_text='【业务说明】设备分类枚举', verbose_name='设备类型')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='【业务说明】软删除标记；【用法】设备报废或误录入删除时置为False，不物理删除以保留历史数据', verbose_name='是否有效')),
                ('bind_at', models.DateTimeField(blank=True, help_text='【业务说明】发放给当前患者的时间，每次绑定更新', null=True, verbose_name='最近绑定时间')),
                ('last_active_at', models.DateTimeField(blank=True, help_text='【业务说明】最后一次上报数据或心跳的时间，用于判断设备是否离线', null=True, verbose_name='最后活跃时间')),
                ('current_patient', models.ForeignKey(blank=True, help_text='【业务说明】当前设备在谁手上；【用法】库存状态时为 NULL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='users.patientprofile', verbose_name='当前绑定患者')),
            ],
            options={
                'verbose_name': '智能设备',
                'verbose_name_plural': '设备库',
                'indexes': [models.Index(fields=['device_type', 'last_active_at'], name='core_device_device__a30390_idx')],
            },
        ),
    ]
