# Generated by Django 5.2.8 on 2025-12-01 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_device"),
        ("users", "0012_remove_patientprofile_device_sn"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "反馈问题"), (2, "提出建议")],
                        default=1,
                        verbose_name="反馈类型",
                    ),
                ),
                ("content", models.TextField(max_length=500, verbose_name="反馈内容")),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="联系方式"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "待处理"), (2, "处理中"), (3, "已解决")],
                        default=1,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="users.patientprofile",
                        verbose_name="患者",
                    ),
                ),
            ],
            options={
                "verbose_name": "意见反馈",
                "verbose_name_plural": "意见反馈",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FeedbackImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="feedback/%Y/%m/", verbose_name="图片"),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.feedback",
                        verbose_name="反馈",
                    ),
                ),
            ],
            options={
                "verbose_name": "反馈图片",
                "verbose_name_plural": "反馈图片",
            },
        ),
    ]
