# Generated by Django 5.2.8 on 2025-12-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_feedback_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text='【说明】程序调用用的标识，如 "about_us"、"user_agreement"、"privacy_policy"、"informed_consent"；创建后请勿随意修改。',
                        max_length=50,
                        unique=True,
                        verbose_name="唯一标识 Key",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="【说明】文案标题，例如“用户协议”。",
                        max_length=100,
                        verbose_name="标题",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="【说明】支持 Markdown 语法，自动渲染为 HTML；可使用标题、列表、加粗等格式。",
                        verbose_name="正文内容（Markdown）",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text='【说明】可选版本号，例如 "1.0"、"2025.01"。',
                        max_length=20,
                        verbose_name="版本号",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="【说明】控制该文案是否对前端可见。",
                        verbose_name="是否启用",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统文案/协议",
                "verbose_name_plural": "系统文案/协议",
                "ordering": ("-updated_at",),
            },
        ),
    ]
