# Generated by Django 5.2.8 on 2025-12-02 04:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_device_current_patient_remove_feedback_user_and_more"),
        ("users", "0012_remove_patientprofile_device_sn"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckupLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="项目名称")),
                (
                    "code",
                    models.CharField(
                        help_text="英文编码，例如 BLOOD_ROUTINE/CT_CHEST。",
                        max_length=50,
                        unique=True,
                        verbose_name="项目编码",
                    ),
                ),
                (
                    "default_freq_days",
                    models.PositiveIntegerField(
                        default=21, verbose_name="默认建议频率(天)"
                    ),
                ),
                (
                    "category",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "影像"), (2, "血液"), (3, "功能")],
                        default=1,
                        verbose_name="分类",
                    ),
                ),
                (
                    "related_report_type",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "未分类"),
                            (1, "胸部CT"),
                            (2, "血常规"),
                            (3, "生化检查"),
                            (4, "肿瘤标志物"),
                        ],
                        help_text="上传该报告类型时自动核销任务。",
                        null=True,
                        verbose_name="关联报告类型",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序权重"),
                ),
            ],
            options={
                "verbose_name": "复查项目",
                "verbose_name_plural": "复查项目",
                "db_table": "core_checkup_library",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="MonitoringConfig",
            fields=[
                (
                    "patient",
                    models.OneToOneField(
                        help_text="绑定的患者档案；删除患者时自动清理配置。",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="monitoring_config",
                        serialize=False,
                        to="users.patientprofile",
                        verbose_name="患者",
                    ),
                ),
                (
                    "check_freq_days",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="监测任务的生成间隔天数，默认每日一次。",
                        verbose_name="监测频率(天)",
                    ),
                ),
                (
                    "enable_temp",
                    models.BooleanField(default=False, verbose_name="启用体温监测"),
                ),
                (
                    "last_gen_date_temp",
                    models.DateField(
                        blank=True, null=True, verbose_name="体温上次生成日期"
                    ),
                ),
                (
                    "enable_spo2",
                    models.BooleanField(default=True, verbose_name="启用血氧监测"),
                ),
                (
                    "last_gen_date_spo2",
                    models.DateField(
                        blank=True, null=True, verbose_name="血氧上次生成日期"
                    ),
                ),
                (
                    "enable_weight",
                    models.BooleanField(default=False, verbose_name="启用体重监测"),
                ),
                (
                    "last_gen_date_weight",
                    models.DateField(
                        blank=True, null=True, verbose_name="体重上次生成日期"
                    ),
                ),
                (
                    "enable_bp",
                    models.BooleanField(default=False, verbose_name="启用血压监测"),
                ),
                (
                    "last_gen_date_bp",
                    models.DateField(
                        blank=True, null=True, verbose_name="血压上次生成日期"
                    ),
                ),
                (
                    "enable_step",
                    models.BooleanField(default=False, verbose_name="启用步数监测"),
                ),
                (
                    "last_gen_date_step",
                    models.DateField(
                        blank=True, null=True, verbose_name="步数上次生成日期"
                    ),
                ),
                (
                    "daily_check_time",
                    models.TimeField(
                        default=datetime.time(9, 0),
                        help_text="每天调度监测任务的时间。",
                        verbose_name="每日生成时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "监测配置",
                "verbose_name_plural": "监测配置",
                "db_table": "core_monitoring_configs",
            },
        ),
        migrations.CreateModel(
            name="TreatmentCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="疗程名称")),
                ("start_date", models.DateField(verbose_name="开始日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "cycle_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "21 天"), (2, "28 天"), (9, "自定义")],
                        default=1,
                        verbose_name="周期类型",
                    ),
                ),
                (
                    "cycle_days",
                    models.PositiveIntegerField(default=21, verbose_name="周期天数"),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "进行中"), (2, "已结束"), (3, "已终止")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_cycles",
                        to="users.patientprofile",
                        verbose_name="患者",
                    ),
                ),
            ],
            options={
                "verbose_name": "治疗疗程",
                "verbose_name_plural": "治疗疗程",
                "db_table": "core_treatment_cycles",
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="PlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "用药"), (2, "检查"), (3, "随访")],
                        default=1,
                        verbose_name="类型",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(max_length=100, verbose_name="项目名称"),
                ),
                (
                    "drug_dosage",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="单次用量"
                    ),
                ),
                (
                    "drug_usage",
                    models.CharField(blank=True, max_length=50, verbose_name="用法"),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "按天"),
                            ("WEEKLY", "按周"),
                            ("CUSTOM", "自定义"),
                        ],
                        default="DAILY",
                        max_length=20,
                        verbose_name="调度类型",
                    ),
                ),
                (
                    "schedule_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="当 schedule_type=CUSTOM 时使用，例如 [1,8,15]。",
                        verbose_name="调度天数",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "生效"), (0, "停用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "priority_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1st_line", "一线"),
                            ("2nd_line", "二线"),
                            ("maintenance", "维持"),
                        ],
                        max_length=20,
                        verbose_name="治疗阶段",
                    ),
                ),
                (
                    "interaction_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='随访问卷/复查注意事项配置，例如 {"modules":["pain"]}',
                        verbose_name="交互配置",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_items",
                        to="core.medication",
                        verbose_name="关联药物",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_items",
                        to="core.treatmentcycle",
                        verbose_name="所属疗程",
                    ),
                ),
            ],
            options={
                "verbose_name": "疗程计划条目",
                "verbose_name_plural": "疗程计划条目",
                "db_table": "core_plan_items",
            },
        ),
        migrations.CreateModel(
            name="DailyTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_date", models.DateField(verbose_name="任务日期")),
                (
                    "task_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "用药"), (2, "检查"), (3, "随访")],
                        verbose_name="任务类型",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="任务标题")),
                ("detail", models.TextField(blank=True, verbose_name="任务描述")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "未做"), (1, "已完成"), (2, "已忽略")],
                        default=0,
                        verbose_name="完成状态",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=False, verbose_name="是否锁定"),
                ),
                (
                    "related_report_type",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "未分类"),
                            (1, "胸部CT"),
                            (2, "血常规"),
                            (3, "生化检查"),
                            (4, "肿瘤标志物"),
                        ],
                        null=True,
                        verbose_name="关联报告类型",
                    ),
                ),
                (
                    "interaction_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="生成任务时从 plan_item.interaction_config 拷贝的快照。",
                        verbose_name="交互配置快照",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_tasks",
                        to="users.patientprofile",
                        verbose_name="患者",
                    ),
                ),
                (
                    "plan_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_tasks",
                        to="core.planitem",
                        verbose_name="来源计划",
                    ),
                ),
            ],
            options={
                "verbose_name": "每日任务",
                "verbose_name_plural": "每日任务",
                "db_table": "core_daily_tasks",
                "indexes": [
                    models.Index(
                        fields=["patient", "task_date"],
                        name="idx_core_task_patient_date",
                    )
                ],
            },
        ),
    ]
