# Generated by Django 5.2.8 on 2025-12-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_checkuplibrary_monitoringconfig_treatmentcycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentcycle',
            name='cycle_type',
        ),
        migrations.AlterField(
            model_name='checkuplibrary',
            name='related_report_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '未分类'), (1, '胸部CT'), (2, '血常规'), (3, '生化检查'), (4, '肿瘤标志物'), (5, '心电图')], help_text='上传该报告类型时自动核销任务。', null=True, verbose_name='关联报告类型'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='related_report_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '未分类'), (1, '胸部CT'), (2, '血常规'), (3, '生化检查'), (4, '肿瘤标志物'), (5, '心电图')], null=True, verbose_name='关联报告类型'),
        ),
    ]
