# Generated by Django 5.2.8 on 2025-12-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_treatmentcycle_cycle_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkuplibrary",
            name="default_freq_days",
        ),
        migrations.AddField(
            model_name="checkuplibrary",
            name="schedule_days_template",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="周期天数列表，例如 [3, 8] 或 [1,2,...,21]。",
                verbose_name="推荐执行天(周期内)",
            ),
        ),
    ]
