# Generated by Django 5.2.8 on 2025-12-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_checkuplibrary_default_freq_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="default_cycle",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="【说明】周期天数模板，例如 [1, 8, 15]；留空表示由医生自定义。",
                verbose_name="推荐执行天(周期内)",
            ),
        ),
    ]
