# Generated by Django 5.2.8 on 2025-12-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_medication_default_cycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowupLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="随访名称")),
                (
                    "code",
                    models.CharField(
                        help_text="唯一英文编码，例如 FOLLOW_PAIN、FOLLOW_SLEEP。",
                        max_length=50,
                        unique=True,
                        verbose_name="随访编码",
                    ),
                ),
                (
                    "schedule_days_template",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="周期内执行的 DayIndex 集合，例如 [7, 14, 21]。",
                        verbose_name="推荐执行天(周期内)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序权重"),
                ),
            ],
            options={
                "verbose_name": "随访模板",
                "verbose_name_plural": "随访模板",
                "db_table": "core_followup_library",
                "ordering": ("sort_order", "name"),
            },
        ),
    ]
