# Generated by Django 5.2.8 on 2025-12-02 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_followuplibrary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="followuplibrary",
            options={
                "ordering": ("sort_order", "name"),
                "verbose_name": "随访项目",
                "verbose_name_plural": "随访项目",
            },
        ),
        migrations.RemoveField(
            model_name="planitem",
            name="schedule_type",
        ),
        migrations.AddField(
            model_name="planitem",
            name="checkup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plan_items",
                to="core.checkuplibrary",
                verbose_name="复查模板",
            ),
        ),
        migrations.AddField(
            model_name="planitem",
            name="followup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plan_items",
                to="core.followuplibrary",
                verbose_name="随访模板",
            ),
        ),
        migrations.AlterField(
            model_name="planitem",
            name="category",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "用药"), (2, "检查"), (3, "随访")], verbose_name="类型"
            ),
        ),
        migrations.AlterField(
            model_name="planitem",
            name="medicine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plan_items",
                to="core.medication",
                verbose_name="药品模板",
            ),
        ),
        migrations.AddIndex(
            model_name="planitem",
            index=models.Index(fields=["cycle", "category"], name="idx_cycle_category"),
        ),
    ]
