# Generated by Django 5.2.8 on 2025-12-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_followuplibrary_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='default_cycle',
            new_name='schedule_days_template',
        ),
    ]
