# Generated by Django 5.2.8 on 2025-12-31 00:00

from decimal import Decimal

from django.core.management.color import no_style
from django.db import migrations

RAW_DATA = """
TOTAL questionnaires=9, questions=60, options=260

[Questionnaire] id=6 | sort=1 | active=True | code=Q_PHYSICAL | name=体能评分
  [Question] id=44 | seq=2 | required=True | type=SINGLE | weight=1.00 | section=- | text=您近期日常活动能力如何？
    [Option] id=197 | seq=1 | text=A. 我完全正常，没有任何症状，和生病前一样能进行各种活动（包括跑步、提重物等）。 | value=0 | score=0.00
    [Option] id=198 | seq=2 | text=B. 我有轻微症状（如咳嗽、轻微疼痛），不能做剧烈运动，但可以进行轻体力工作（如简单的家务、办公室工作）。 | value=1 | score=1.00
    [Option] id=199 | seq=3 | text=C. 我生活能自理（吃饭、穿衣、洗漱），白天能起床走动，但无法进行工作。白天卧床时间少于一半。 | value=2 | score=2.00
    [Option] id=200 | seq=4 | text=D. 我生活只能部分自理，大部分时间需要卧床或坐在椅子上。白天卧床时间超过一半。 | value=3 | score=3.00
    [Option] id=201 | seq=5 | text=E. 我完全不能自理，需要别人完全照顾，全天卧床或坐在椅子上。 | value=4 | score=4.00

[Questionnaire] id=7 | sort=2 | active=True | code=Q_BREATH | name=呼吸困难评估
  [Question] id=46 | seq=2 | required=True | type=SINGLE | weight=1.00 | section=- | text=您在活动时感到气短/呼吸困难的程度？
    [Option] id=207 | seq=1 | text=A. 我只在剧烈运动（如快跑、爬高层楼梯）时才感到气喘。 | value=0 | score=0.00
    [Option] id=208 | seq=2 | text=B. 我在平地快走或上小斜坡时会感到气喘。 | value=1 | score=1.00
    [Option] id=209 | seq=3 | text=C. 我在平地行走时，因为气喘必须比同龄人走得慢，或者按自己节奏走几分钟就得停下来喘口气。 | value=2 | score=2.00
    [Option] id=210 | seq=4 | text=D. 我在平地走约 100 米，或才几分钟，就不得不停下来喘口气。 | value=3 | score=3.00
    [Option] id=211 | seq=5 | text=E. 我因为气喘太严重而无法离开房间，或者穿脱衣服时都会气喘。 | value=4 | score=4.00

[Questionnaire] id=5 | sort=3 | active=True | code=Q_COUGH | name=咳嗽与痰色评估
  [Question] id=38 | seq=1 | required=True | type=SINGLE | weight=1.00 | section=- | text=最近的咳嗽情况如何？
    [Option] id=166 | seq=1 | text=近期无咳嗽情况。 | value=0 | score=0.00
    [Option] id=167 | seq=2 | text=偶尔有点轻微咳嗽，但不影响说话和吃饭，也不用吃药。 | value=1 | score=1.00
    [Option] id=168 | seq=3 | text=需要吃止咳药才能压住，或者咳嗽打断聊天、做家务。 | value=2 | score=2.00
    [Option] id=169 | seq=4 | text=严重影响睡眠，甚至吃饭、穿衣服都受影响，感觉很痛苦。 | value=3 | score=3.00
  [Question] id=39 | seq=2 | required=True | type=SINGLE | weight=1.00 | section=- | text=最近痰液性状情况如何？
    [Option] id=170 | seq=1 | text=无痰，或只是干咳。 | value=0 | score=0.00
    [Option] id=171 | seq=2 | text=像唾沫或蛋清一样，不浑浊。 | value=0 | score=0.00
    [Option] id=172 | seq=3 | text=痰有点稠，颜色稍微有点黄，但不算很深。 | value=1 | score=1.00
    [Option] id=173 | seq=4 | text=像脓一样的深黄色或绿色，很粘稠，甚至是一坨一坨的。 | value=3 | score=3.00
  [Question] id=40 | seq=3 | required=True | type=SINGLE | weight=1.00 | section=- | text=咳嗽或痰中是否带血？
    [Option] id=174 | seq=1 | text=完全没血，痰很干净。 | value=0 | score=0.00
    [Option] id=175 | seq=2 | text=痰里夹杂着几条红血丝，或者痰带点粉红色。 | value=3 | score=3.00
    [Option] id=176 | seq=3 | text=咳出来的全是红色的血，大概有一两口那么多。 | value=5 | score=5.00
    [Option] id=177 | seq=4 | text=血量很大，止不住。 | value=9 | score=9.00
  [Question] id=41 | seq=4 | required=True | type=SINGLE | weight=1.00 | section=- | text=发生以上情况时的体温情况如何？
    [Option] id=178 | seq=1 | text=正常，37℃左右。 | value=0 | score=0.00
    [Option] id=179 | seq=2 | text=有点低烧 (37.3℃ - 38.0℃)。 | value=0 | score=0.00
    [Option] id=180 | seq=3 | text=发高烧 (38.0℃以上，或者感觉身体发冷打寒战)。 | value=0 | score=0.00
    [Option] id=181 | seq=4 | text=未测量，不清楚。 | value=0 | score=0.00
  [Question] id=42 | seq=5 | required=True | type=SINGLE | weight=1.00 | section=- | text=发生以上情况时的血氧情况如何？
    [Option] id=182 | seq=1 | text=正常，95以上。 | value=0 | score=0.00
    [Option] id=183 | seq=2 | text=略低，90-94之间。 | value=0 | score=0.00
    [Option] id=184 | seq=3 | text=很低，低于90。 | value=0 | score=0.00
    [Option] id=185 | seq=4 | text=未测量，不清楚。 | value=0 | score=0.00

[Questionnaire] id=2 | sort=4 | active=True | code=Q_APPETITE | name=食欲评估
  [Question] id=9 | seq=1 | required=True | type=SINGLE | weight=1.00 | section=- | text=与平时（患病前）相比，您现在的进食量大约是多少？
    [Option] id=41 | seq=1 | text=进食正常或比平时多 | value=0 | score=0.00
    [Option] id=42 | seq=2 | text=约为平时的 70%-90% | value=1 | score=1.00
    [Option] id=43 | seq=3 | text=约为平时的 50%-60% | value=2 | score=2.00
    [Option] id=44 | seq=4 | text=少于平时的 50% 或几乎不吃 | value=4 | score=4.00
  [Question] id=10 | seq=2 | required=True | type=SINGLE | weight=1.00 | section=- | text=最近 1 个月内，您的体重是否有下降？
    [Option] id=45 | seq=1 | text=无下降或体重增加 | value=0 | score=0.00
    [Option] id=46 | seq=2 | text=下降约 1-3 kg | value=1 | score=1.00
    [Option] id=47 | seq=3 | text=下降 > 3 kg | value=3 | score=3.00
    [Option] id=48 | seq=4 | text=不清楚，但衣服明显变松 | value=2 | score=2.00
  [Question] id=11 | seq=3 | required=True | type=SINGLE | weight=1.00 | section=- | text=请为您的食欲打分，0分表示“完全没有食欲/看见食物就恶心”，10分表示“食欲极好/很想吃东西”
    [Option] id=49 | seq=1 | text=8-10分 | value=0 | score=0.00
    [Option] id=50 | seq=2 | text=5-7分 | value=1 | score=1.00
    [Option] id=51 | seq=3 | text=3-4分 | value=2 | score=2.00
    [Option] id=52 | seq=4 | text=0-2分 | value=3 | score=3.00
  [Question] id=12 | seq=4 | required=True | type=MULTIPLE | weight=1.00 | section=- | text=是否存在以下影响进食的症状？（多选）
    [Option] id=53 | seq=1 | text=恶心/呕吐 | value=1 | score=1.00
    [Option] id=54 | seq=2 | text=吞咽困难/吞咽痛 | value=1 | score=1.00
    [Option] id=55 | seq=3 | text=口腔溃疡/口干 | value=1 | score=1.00
    [Option] id=56 | seq=4 | text=嗅觉或味觉改变（觉得食物有苦味/金属味） | value=1 | score=1.00
    [Option] id=57 | seq=5 | text=呼吸急促/气短（吃几口就喘） | value=1 | score=1.00
    [Option] id=58 | seq=6 | text=便秘或腹泻 | value=1 | score=1.00
    [Option] id=59 | seq=7 | text=疼痛（胸痛或全身痛） | value=1 | score=1.00
    [Option] id=60 | seq=8 | text=易饱感（吃两口就饱了） | value=1 | score=1.00
    [Option] id=276 | seq=9 | text=无 | value=0 | score=0.00
  [Question] id=13 | seq=5 | required=True | type=SINGLE | weight=1.00 | section=- | text=您最近的活动能力如何？
    [Option] id=61 | seq=1 | text=活动自如，能进行日常散步等活动 | value=0 | score=0.00
    [Option] id=62 | seq=2 | text=容易疲劳，多数时间需要坐着或躺着，但能下地 | value=1 | score=1.00
    [Option] id=63 | seq=3 | text=超过一半时间必须卧床 | value=3 | score=3.00

[Questionnaire] id=4 | sort=5 | active=True | code=Q_PAIN | name=身体疼痛评估
  [Question] id=34 | seq=1 | required=True | type=SINGLE | weight=1.00 | section=- | text=术口/胸膛/肋间
    [Option] id=150 | seq=1 | text=无疼痛 | value=0 | score=0.00
    [Option] id=151 | seq=2 | text=轻度 | value=2 | score=2.00
    [Option] id=152 | seq=3 | text=中度 | value=5 | score=5.00
    [Option] id=153 | seq=4 | text=重度 | value=9 | score=9.00
  [Question] id=35 | seq=2 | required=True | type=SINGLE | weight=1.00 | section=- | text=肩峰/肩背/肩胛
    [Option] id=154 | seq=1 | text=无疼痛 | value=0 | score=0.00
    [Option] id=155 | seq=2 | text=轻度 | value=2 | score=2.00
    [Option] id=156 | seq=3 | text=中度 | value=5 | score=5.00
    [Option] id=157 | seq=4 | text=重度 | value=9 | score=9.00
  [Question] id=36 | seq=3 | required=True | type=SINGLE | weight=1.00 | section=- | text=肋骨/脊柱/骨盆/四肢
    [Option] id=158 | seq=1 | text=无疼痛 | value=0 | score=0.00
    [Option] id=159 | seq=2 | text=轻度 | value=2 | score=2.00
    [Option] id=160 | seq=3 | text=中度 | value=5 | score=5.00
    [Option] id=161 | seq=4 | text=重度 | value=9 | score=9.00
  [Question] id=37 | seq=4 | required=True | type=SINGLE | weight=1.00 | section=- | text=头部
    [Option] id=162 | seq=1 | text=无疼痛 | value=0 | score=0.00
    [Option] id=163 | seq=2 | text=轻度 | value=2 | score=2.00
    [Option] id=164 | seq=3 | text=中度 | value=5 | score=5.00
    [Option] id=165 | seq=4 | text=重度 | value=9 | score=9.00

[Questionnaire] id=1 | sort=6 | active=True | code=Q_SLEEP | name=睡眠质量评估
  [Question] id=1 | seq=1 | required=True | type=SINGLE | weight=1.00 | section=- | text=您最近的睡眠质量是...
    [Option] id=1 | seq=1 | text=非常差 | value=5 | score=5.00
    [Option] id=2 | seq=2 | text=差 | value=4 | score=4.00
    [Option] id=3 | seq=3 | text=一般 | value=3 | score=3.00
    [Option] id=4 | seq=4 | text=好 | value=2 | score=2.00
    [Option] id=5 | seq=5 | text=非常好 | value=1 | score=1.00
  [Question] id=2 | seq=2 | required=True | type=SINGLE | weight=1.00 | section=- | text=睡眠令人恢复精神。
    [Option] id=6 | seq=1 | text=完全没有 | value=5 | score=5.00
    [Option] id=7 | seq=2 | text=一点点 | value=4 | score=4.00
    [Option] id=8 | seq=3 | text=有些 | value=3 | score=3.00
    [Option] id=9 | seq=4 | text=相当多 | value=2 | score=2.00
    [Option] id=10 | seq=5 | text=非常 | value=1 | score=1.00
  [Question] id=3 | seq=3 | required=True | type=SINGLE | weight=1.00 | section=- | text=有睡眠问题。
    [Option] id=11 | seq=1 | text=完全没有 | value=1 | score=1.00
    [Option] id=12 | seq=2 | text=一点点 | value=2 | score=2.00
    [Option] id=13 | seq=3 | text=有些 | value=3 | score=3.00
    [Option] id=14 | seq=4 | text=相当多 | value=4 | score=4.00
    [Option] id=15 | seq=5 | text=非常 | value=5 | score=5.00
  [Question] id=4 | seq=4 | required=True | type=SINGLE | weight=1.00 | section=- | text=难以入睡。
    [Option] id=16 | seq=1 | text=完全没有 | value=1 | score=1.00
    [Option] id=17 | seq=2 | text=一点点 | value=2 | score=2.00
    [Option] id=18 | seq=3 | text=有些 | value=3 | score=3.00
    [Option] id=19 | seq=4 | text=相当多 | value=4 | score=4.00
    [Option] id=20 | seq=5 | text=非常 | value=5 | score=5.00
  [Question] id=5 | seq=5 | required=True | type=SINGLE | weight=1.00 | section=- | text=睡眠不安稳。
    [Option] id=21 | seq=1 | text=完全没有 | value=1 | score=1.00
    [Option] id=22 | seq=2 | text=一点点 | value=2 | score=2.00
    [Option] id=23 | seq=3 | text=有些 | value=3 | score=3.00
    [Option] id=24 | seq=4 | text=相当多 | value=4 | score=4.00
    [Option] id=25 | seq=5 | text=非常 | value=5 | score=5.00
  [Question] id=6 | seq=6 | required=True | type=SINGLE | weight=1.00 | section=- | text=努力尝试入睡。
    [Option] id=26 | seq=1 | text=完全没有 | value=1 | score=1.00
    [Option] id=27 | seq=2 | text=一点点 | value=2 | score=2.00
    [Option] id=28 | seq=3 | text=有些 | value=3 | score=3.00
    [Option] id=29 | seq=4 | text=相当多 | value=4 | score=4.00
    [Option] id=30 | seq=5 | text=非常 | value=5 | score=5.00
  [Question] id=7 | seq=7 | required=True | type=SINGLE | weight=1.00 | section=- | text=担心无法入睡。
    [Option] id=31 | seq=1 | text=完全没有 | value=1 | score=1.00
    [Option] id=32 | seq=2 | text=一点点 | value=2 | score=2.00
    [Option] id=33 | seq=3 | text=有些 | value=3 | score=3.00
    [Option] id=34 | seq=4 | text=相当多 | value=4 | score=4.00
    [Option] id=35 | seq=5 | text=非常 | value=5 | score=5.00
  [Question] id=8 | seq=8 | required=True | type=SINGLE | weight=1.00 | section=- | text=对睡眠感到满意。
    [Option] id=36 | seq=1 | text=完全没有 | value=5 | score=5.00
    [Option] id=37 | seq=2 | text=一点点 | value=4 | score=4.00
    [Option] id=38 | seq=3 | text=有些 | value=3 | score=3.00
    [Option] id=39 | seq=4 | text=相当多 | value=2 | score=2.00
    [Option] id=40 | seq=5 | text=非常 | value=1 | score=1.00

[Questionnaire] id=8 | sort=7 | active=True | code=Q_DEPRESSIVE | name=抑郁评估
  [Question] id=47 | seq=1 | required=True | type=SINGLE | weight=1.00 | section=- | text=做事提不起劲或没有兴趣
    [Option] id=212 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=213 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=214 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=215 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=48 | seq=2 | required=True | type=SINGLE | weight=1.00 | section=- | text=感到心情低落、沮丧或绝望
    [Option] id=216 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=217 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=218 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=219 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=49 | seq=3 | required=True | type=SINGLE | weight=1.00 | section=- | text=入睡困难、睡不安稳或睡眠过多
    [Option] id=220 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=221 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=222 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=223 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=50 | seq=4 | required=True | type=SINGLE | weight=1.00 | section=- | text=感到疲倦或没有活力
    [Option] id=224 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=225 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=226 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=227 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=51 | seq=5 | required=True | type=SINGLE | weight=1.00 | section=- | text=食欲不振或吃太多
    [Option] id=228 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=229 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=230 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=231 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=52 | seq=6 | required=True | type=SINGLE | weight=1.00 | section=- | text=觉得自己很糟或觉得自己很失败，让自己或家人失望
    [Option] id=232 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=233 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=234 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=235 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=53 | seq=7 | required=True | type=SINGLE | weight=1.00 | section=- | text=对事物专注有困难（如看书或看电视时）
    [Option] id=236 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=237 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=238 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=239 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=54 | seq=8 | required=True | type=SINGLE | weight=1.00 | section=- | text=动作或说话速度缓慢；或者相反，烦躁坐立不安
    [Option] id=240 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=241 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=242 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=243 | seq=4 | text=几乎每天 | value=3 | score=2.00
  [Question] id=55 | seq=9 | required=True | type=SINGLE | weight=1.00 | section=- | text=有不如死掉或用某种方式伤害自己的念头
    [Option] id=244 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=245 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=246 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=247 | seq=4 | text=几乎每天 | value=3 | score=3.00

[Questionnaire] id=9 | sort=8 | active=True | code=Q_ANXIETY | name=焦虑评估
  [Question] id=56 | seq=1 | required=True | type=SINGLE | weight=1.00 | section=- | text=感觉神经质、焦虑或急切
    [Option] id=248 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=249 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=250 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=251 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=57 | seq=2 | required=True | type=SINGLE | weight=1.00 | section=- | text=不能停止或无法控制担忧
    [Option] id=252 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=253 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=254 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=255 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=58 | seq=3 | required=True | type=SINGLE | weight=1.00 | section=- | text=对各种各样的事情担忧过多
    [Option] id=256 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=257 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=258 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=259 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=59 | seq=4 | required=True | type=SINGLE | weight=1.00 | section=- | text=很难放松下来（常伴随呼吸急促感）
    [Option] id=260 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=261 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=262 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=263 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=60 | seq=5 | required=True | type=SINGLE | weight=1.00 | section=- | text=由于不安而无法静坐
    [Option] id=264 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=265 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=266 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=267 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=61 | seq=6 | required=True | type=SINGLE | weight=1.00 | section=- | text=变得容易烦恼或急躁
    [Option] id=272 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=273 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=274 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=275 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=62 | seq=7 | required=True | type=SINGLE | weight=1.00 | section=- | text=感到似乎将有可怕的事情发生
    [Option] id=268 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=269 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=270 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=271 | seq=4 | text=几乎每天 | value=3 | score=3.00

[Questionnaire] id=3 | sort=99 | active=False | code=Q_PSYCH | name=心理痛苦分级评估
  [Question] id=14 | seq=1 | required=True | type=SINGLE | weight=1.00 | section=第一部分：痛苦温度计 (DT) | text=请圈出您过去一周内的心理痛苦程度（0分无痛苦，10分极度痛苦）
    [Option] id=64 | seq=1 | text=0分 | value=0 | score=0.00
    [Option] id=65 | seq=2 | text=1分 | value=1 | score=1.00
    [Option] id=66 | seq=3 | text=2分 | value=2 | score=2.00
    [Option] id=67 | seq=4 | text=3分 | value=3 | score=3.00
    [Option] id=68 | seq=5 | text=4分 | value=4 | score=4.00
    [Option] id=69 | seq=6 | text=5分 | value=5 | score=5.00
    [Option] id=70 | seq=7 | text=6分 | value=6 | score=6.00
    [Option] id=71 | seq=8 | text=7分 | value=7 | score=7.00
    [Option] id=72 | seq=9 | text=8分 | value=8 | score=8.00
    [Option] id=73 | seq=10 | text=9分 | value=9 | score=9.00
    [Option] id=74 | seq=11 | text=10分 | value=10 | score=10.00
  [Question] id=15 | seq=2 | required=True | type=SINGLE | weight=1.00 | section=第二部分：近期您生活中出现以下症状的频率有多少？ | text=做事提不起劲或没有兴趣
    [Option] id=75 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=76 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=77 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=78 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=16 | seq=3 | required=True | type=SINGLE | weight=1.00 | section=第二部分：近期您生活中出现以下症状的频率有多少？ | text=感到心情低落、沮丧或绝望
    [Option] id=79 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=80 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=81 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=82 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=17 | seq=4 | required=True | type=SINGLE | weight=1.00 | section=第二部分：近期您生活中出现以下症状的频率有多少？ | text=入睡困难、睡不安稳或睡眠过多
    [Option] id=83 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=84 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=85 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=86 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=18 | seq=5 | required=True | type=SINGLE | weight=1.00 | section=第二部分：近期您生活中出现以下症状的频率有多少？ | text=感到疲倦或没有活力
    [Option] id=87 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=88 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=89 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=90 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=19 | seq=6 | required=True | type=SINGLE | weight=1.00 | section=第二部分：近期您生活中出现以下症状的频率有多少？ | text=食欲不振或吃太多
    [Option] id=91 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=92 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=93 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=94 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=20 | seq=7 | required=True | type=SINGLE | weight=1.00 | section=第二部分：近期您生活中出现以下症状的频率有多少？ | text=觉得自己很糟或觉得自己很失败，让自己或家人失望
    [Option] id=95 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=96 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=97 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=98 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=21 | seq=8 | required=True | type=SINGLE | weight=1.00 | section=第二部分：近期您生活中出现以下症状的频率有多少？ | text=对事物专注有困难（如看报纸或看电视时）
    [Option] id=99 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=100 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=101 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=102 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=22 | seq=9 | required=True | type=SINGLE | weight=1.00 | section=第二部分：近期您生活中出现以下症状的频率有多少？ | text=动作或说话速度缓慢；或者相反，烦躁坐立不安
    [Option] id=103 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=104 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=105 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=106 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=23 | seq=10 | required=True | type=SINGLE | weight=1.00 | section=第二部分：近期您生活中出现以下症状的频率有多少？ | text=有不如死掉或用某种方式伤害自己的念头
    [Option] id=107 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=108 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=109 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=110 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=24 | seq=11 | required=True | type=SINGLE | weight=1.00 | section=第三部分：近期您生活中出现以下症状的频率有多少？ | text=感觉神经质、焦虑或急切
    [Option] id=111 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=112 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=113 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=114 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=25 | seq=12 | required=True | type=SINGLE | weight=1.00 | section=第三部分：近期您生活中出现以下症状的频率有多少？ | text=不能停止或无法控制担忧
    [Option] id=115 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=116 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=117 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=118 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=26 | seq=13 | required=True | type=SINGLE | weight=1.00 | section=第三部分：近期您生活中出现以下症状的频率有多少？ | text=对各种各样的事情担忧过多
    [Option] id=119 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=120 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=121 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=122 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=27 | seq=14 | required=True | type=SINGLE | weight=1.00 | section=第三部分：近期您生活中出现以下症状的频率有多少？ | text=很难放松下来（常伴随呼吸急促感）
    [Option] id=123 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=124 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=125 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=126 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=28 | seq=15 | required=True | type=SINGLE | weight=1.00 | section=第三部分：近期您生活中出现以下症状的频率有多少？ | text=由于不安而无法静坐
    [Option] id=127 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=128 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=129 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=130 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=29 | seq=16 | required=True | type=SINGLE | weight=1.00 | section=第三部分：近期您生活中出现以下症状的频率有多少？ | text=变得容易烦恼或急躁
    [Option] id=131 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=132 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=133 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=134 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=30 | seq=17 | required=True | type=SINGLE | weight=1.00 | section=第三部分：近期您生活中出现以下症状的频率有多少？ | text=感到似乎将有可怕的事情发生
    [Option] id=135 | seq=1 | text=完全不会 | value=0 | score=0.00
    [Option] id=136 | seq=2 | text=好几天 | value=1 | score=1.00
    [Option] id=137 | seq=3 | text=一半以上天数 | value=2 | score=2.00
    [Option] id=138 | seq=4 | text=几乎每天 | value=3 | score=3.00
  [Question] id=31 | seq=18 | required=True | type=MULTIPLE | weight=1.00 | section=第四部分：如果您感到痛苦或情绪不佳，主要原因是什么？（多选） | text=躯体症状（如果您感到痛苦，主要原因包含哪些？）
    [Option] id=139 | seq=1 | text=呼吸困难/气短 | value=0 | score=0.00
    [Option] id=140 | seq=2 | text=疼痛 | value=0 | score=0.00
    [Option] id=141 | seq=3 | text=咳嗽/咳痰 | value=0 | score=0.00
    [Option] id=142 | seq=4 | text=乏力 | value=0 | score=0.00
    [Option] id=143 | seq=5 | text=睡眠问题 | value=0 | score=0.00
  [Question] id=32 | seq=19 | required=True | type=MULTIPLE | weight=1.00 | section=第四部分：如果您感到痛苦或情绪不佳，主要原因是什么？（多选） | text=实际问题（如果您感到痛苦，主要原因包含哪些？）
    [Option] id=144 | seq=1 | text=经济压力 | value=0 | score=0.00
    [Option] id=145 | seq=2 | text=就医/复查不便 | value=0 | score=0.00
    [Option] id=146 | seq=3 | text=没有人照顾 | value=0 | score=0.00
  [Question] id=33 | seq=20 | required=True | type=MULTIPLE | weight=1.00 | section=第四部分：如果您感到痛苦或情绪不佳，主要原因是什么？（多选） | text=疾病认知（如果您感到痛苦，主要原因包含哪些？）
    [Option] id=147 | seq=1 | text=担心复发/转移 | value=0 | score=0.00
    [Option] id=148 | seq=2 | text=对治疗副作用的恐惧 | value=0 | score=0.00
    [Option] id=149 | seq=3 | text=不了解康复知识 | value=0 | score=0.00
"""

QUESTIONNAIRE_CATEGORY = 3


def _parse_line(line):
    fields = {}
    for part in line.split(" | "):
        if "=" not in part:
            continue
        key, value = part.split("=", 1)
        fields[key.strip()] = value.strip()
    return fields


def _parse_seed_data(raw_data):
    questionnaires = []
    questions = []
    options = []
    current_questionnaire_id = None
    current_question_id = None
    expected_counts = None

    for raw_line in raw_data.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("TOTAL"):
            expected_counts = {}
            parts = line[len("TOTAL ") :].split(", ")
            for part in parts:
                key, value = part.split("=", 1)
                expected_counts[key.strip()] = int(value.strip())
            continue

        if line.startswith("[Questionnaire]"):
            fields = _parse_line(line[len("[Questionnaire] ") :])
            current_questionnaire_id = int(fields["id"])
            current_question_id = None
            questionnaires.append(
                {
                    "id": current_questionnaire_id,
                    "sort_order": int(fields["sort"]),
                    "is_active": fields["active"] == "True",
                    "code": fields["code"],
                    "name": fields["name"],
                }
            )
            continue

        if line.startswith("[Question]"):
            if current_questionnaire_id is None:
                raise ValueError("Question line without questionnaire context.")
            fields = _parse_line(line[len("[Question] ") :])
            current_question_id = int(fields["id"])
            questions.append(
                {
                    "id": current_question_id,
                    "questionnaire_id": current_questionnaire_id,
                    "seq": int(fields["seq"]),
                    "is_required": fields["required"] == "True",
                    "q_type": fields["type"],
                    "weight": Decimal(fields["weight"]),
                    "section": "" if fields["section"] == "-" else fields["section"],
                    "text": fields["text"],
                }
            )
            continue

        if line.startswith("[Option]"):
            if current_question_id is None:
                raise ValueError("Option line without question context.")
            fields = _parse_line(line[len("[Option] ") :])
            options.append(
                {
                    "id": int(fields["id"]),
                    "question_id": current_question_id,
                    "seq": int(fields["seq"]),
                    "text": fields["text"],
                    "value": "" if fields["value"] == "-" else fields["value"],
                    "score": Decimal(fields["score"]),
                }
            )

    if expected_counts:
        if expected_counts.get("questionnaires") != len(questionnaires):
            raise ValueError("Questionnaire count mismatch.")
        if expected_counts.get("questions") != len(questions):
            raise ValueError("Question count mismatch.")
        if expected_counts.get("options") != len(options):
            raise ValueError("Option count mismatch.")

    return questionnaires, questions, options


def _reset_sequences(schema_editor, models):
    sql_statements = schema_editor.connection.ops.sequence_reset_sql(
        no_style(), models
    )
    for sql in sql_statements:
        schema_editor.execute(sql)


def reseed_questionnaires(apps, schema_editor):
    Questionnaire = apps.get_model("core", "Questionnaire")
    QuestionnaireQuestion = apps.get_model("core", "QuestionnaireQuestion")
    QuestionnaireOption = apps.get_model("core", "QuestionnaireOption")
    PlanItem = apps.get_model("core", "PlanItem")
    DailyTask = apps.get_model("core", "DailyTask")
    HealthMetric = apps.get_model("health_data", "HealthMetric")

    HealthMetric._base_manager.filter(questionnaire_submission__isnull=False).delete()
    DailyTask.objects.filter(task_type=QUESTIONNAIRE_CATEGORY).delete()
    PlanItem.objects.filter(category=QUESTIONNAIRE_CATEGORY).delete()

    QuestionnaireOption.objects.all().delete()
    QuestionnaireQuestion.objects.all().delete()
    Questionnaire.objects.all().delete()

    questionnaires_data, questions_data, options_data = _parse_seed_data(RAW_DATA)

    Questionnaire.objects.bulk_create(
        [Questionnaire(**data) for data in questionnaires_data]
    )
    QuestionnaireQuestion.objects.bulk_create(
        [QuestionnaireQuestion(**data) for data in questions_data]
    )
    QuestionnaireOption.objects.bulk_create(
        [QuestionnaireOption(**data) for data in options_data]
    )

    _reset_sequences(
        schema_editor,
        [Questionnaire, QuestionnaireQuestion, QuestionnaireOption],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_alter_dailytask_status"),
        ("health_data", "0012_alter_healthmetric_metric_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionnaire",
            name="metric_type",
        ),
        migrations.RunPython(reseed_questionnaires, migrations.RunPython.noop),
    ]
