# Generated by Django 5.2.8 on 2025-12-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="service_content",
            field=models.TextField(
                blank=True,
                help_text="【说明】服务包具体内容及权益说明；可填写几百字的描述。",
                verbose_name="服务包内容",
            ),
        ),
    ]
