# Generated by Codex on 2026-07-09

import django.db.models.deletion
from django.db import migrations, models


def seed_hrt_provider(apps, schema_editor):
    DeviceProvider = apps.get_model("business_support", "DeviceProvider")
    Device = apps.get_model("business_support", "Device")
    provider, _ = DeviceProvider.objects.get_or_create(
        code="HRT",
        defaults={
            "name": "HRT",
            "is_active": True,
            "description": "默认智能手表数据厂商。",
        },
    )
    Device.objects.filter(provider__isnull=True).update(provider=provider)


def unseed_hrt_provider(apps, schema_editor):
    DeviceProvider = apps.get_model("business_support", "DeviceProvider")
    Device = apps.get_model("business_support", "Device")
    try:
        provider = DeviceProvider.objects.get(code="HRT")
    except DeviceProvider.DoesNotExist:
        return
    Device.objects.filter(provider=provider).update(provider=None)
    if not provider.devices.exists():
        provider.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("business_support", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="【业务说明】记录数据首次写入时间；【用法】只读字段，自动写入；【示例】2025-01-01 09:00;【参数】无；【返回值】datetime",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="【业务说明】记录最新修改时间，方便比对变更；【用法】ORM 保存时自动更新；【示例】2025-01-02 18:30;【参数】无；【返回值】datetime",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="系统内稳定编码，例如 HRT。",
                        max_length=32,
                        unique=True,
                        verbose_name="厂商编码",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="后台展示名称，例如 HRT。",
                        max_length=64,
                        verbose_name="厂商名称",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="停用后不再接收该厂商新上报数据。",
                        verbose_name="是否启用",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="厂商接口、联系人或运维说明。",
                        verbose_name="说明",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备厂商",
                "verbose_name_plural": "设备厂商",
                "ordering": ("code",),
            },
        ),
        migrations.AddField(
            model_name="device",
            name="provider",
            field=models.ForeignKey(
                help_text="【业务说明】设备数据来源厂商",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="business_support.deviceprovider",
                verbose_name="设备厂商",
            ),
        ),
        migrations.RunPython(seed_hrt_provider, unseed_hrt_provider),
    ]
