# Generated by Django 5.2.8 on 2026-07-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0025_reportimage_review_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmetric',
            name='metric_type',
            field=models.CharField(choices=[('M_BP', '血压'), ('M_SPO2', '血氧'), ('M_HR', '心率'), ('M_STEPS', '步数'), ('M_WEIGHT', '体重'), ('M_TEMP', '体温'), ('M_GLU', '血糖'), ('M_KETONE', '血酮'), ('M_UA', '尿酸'), ('M_USE_MEDICATED', '用药情况'), ('M_CHECKUP', '复查')], max_length=50, verbose_name='指标类型'),
        ),
    ]
